
import { Translation } from './types';

export const TRANS: Record<'en' | 'zh', Translation> = {
  en: {
    lang_btn: 'Switch to 中文',
    title: 'Client Intake Form',
    subtitle: 'Please fill out before treatment',
    lbl_name: 'Client Name',
    lbl_email: 'Email Address',
    lbl_ins: 'Private Health Fund (Optional)',
    privacy: 'Your details are kept private and secure.',
    lbl_area: 'Main Pain Area (Max 3)',
    lbl_side: 'Which side?',
    lbl_duration: 'How long have you had it?',
    lbl_desc: 'Pain Sensation',
    lbl_level: 'Pain Intensity (0-10)',
    lbl_job: 'Your Daily Activity / Job',
    lbl_sit: 'Sitting Hours per Day',
    lbl_goal: 'Goal for Today',
    lbl_note: 'Medical History / Notes',
    lbl_consent: 'I confirm the above is correct and consent to treatment.',
    btn_submit: 'SUBMIT',
    loading: 'Processing...',
    success: 'Success',
    result_title: 'Clinical Assessment Report',
    btn_new: 'Start New Client',
    opt_area: ["Neck", "Shoulders", "Upper Back", "Lower Back", "Hips", "Legs", "Knees", "Feet", "Head", "Arms"],
    opt_side: ["Both sides", "Left side", "Right side", "Center"],
    opt_dur: ["< 24 hours (New)", "1 week", "1 month", "> 3 months (Long term)"],
    opt_desc: ["Sharp", "Dull/Aching", "Stiff", "Numb/Tingling", "Burning"],
    opt_job: ["Desk Job", "Standing Job", "Physical Labor", "Athlete", "Retired"],
    opt_goal: ["Pain Relief", "Relaxation", "Better Sleep", "Deep Tissue Release"],
    opt_sit: ["<2h", "2-4h", "4-8h", "8h+"],
    required_warning: "⚠️ Name and Pain Area are required.",
    consent_warning: "⚠️ Please check the box to consent.",
    nav_client: "Customer Intake",
    nav_staff: "Reception Desk",
    staff_title: "Client Management Dashboard",
    btn_gen_report: "Generate AI Report",
    btn_print: "Print Report",
    status_pending: "Waiting for AI",
    status_done: "Report Ready",
    no_records: "No intake forms received yet.",
    lbl_clear_all: "Clear All Records"
  },
  zh: {
    lang_btn: 'Switch to English',
    title: '客户健康评估表',
    subtitle: '理疗前请填写',
    lbl_name: '客户姓名',
    lbl_email: '电子邮箱',
    lbl_ins: '私人医疗保险 (选填)',
    privacy: '您的信息将被严格保密。',
    lbl_area: '主要疼痛部位 (最多选3项)',
    lbl_side: '侧别',
    lbl_duration: '持续时间',
    lbl_desc: '疼痛感觉',
    lbl_level: '疼痛等级 (0-10)',
    lbl_job: '日常活动 / 职业',
    lbl_sit: '每天久坐时长',
    lbl_goal: '今天治疗目标',
    lbl_note: '病史 / 备注',
    lbl_consent: '我确认信息属实并同意理疗。',
    btn_submit: '送出',
    loading: '正在分析...',
    success: '评估已生成',
    result_title: 'AI 诊断报告',
    btn_new: '接待下一位',
    opt_area: ["Neck (颈)", "Shoulders (肩)", "Upper Back (上背)", "Lower Back (下腰)", "Hips (臀)", "Legs (腿)", "Knees (膝)", "Feet (足)", "Head (头)", "Arms (手)"],
    opt_side: ["Both (两侧)", "Left (左)", "Right (右)", "Center (中)"],
    opt_dur: ["<24h (新伤)", "1wk (一周)", "1m (一月)", ">3m (长期)"],
    opt_desc: ["Sharp (刺痛)", "Dull (酸痛)", "Stiff (僵硬)", "Numb (麻木)", "Burning (灼烧)"],
    opt_job: ["Desk Job (办公)", "Standing (久站)", "Labor (体力)", "Athlete (运动)", "Retired (退休)"],
    opt_goal: ["Pain Relief (止痛)", "Relax (放松)", "Sleep (助眠)", "Tissue (松解)"],
    opt_sit: ["<2h", "2-4h", "4-8h", "8h+"],
    required_warning: "⚠️ 请填写姓名和疼痛部位。",
    consent_warning: "⚠️ 请勾选同意框。",
    nav_client: "客户登记",
    nav_staff: "前台管理",
    staff_title: "客户信息管理中心",
    btn_gen_report: "生成 AI 报告",
    btn_print: "打印报告",
    status_pending: "待生成报告",
    status_done: "报告已就绪",
    no_records: "暂无客户提交信息。",
    lbl_clear_all: "清空所有记录"
  }
};
